### ISSUE TITLE
Missing res folder

### ISSUE THREAD

**Issue by subsoap** [appodeal/appodeal-monkeyx-demo#3]
There is a res folder which is needed but not included in this repo

**Comment by Tamplier** [comment]
@subsoap 
Res folder is no longer needed. After first build attempt open your [project]\[build]\android\build.properties in your favorite text editor and add following lines:

`android.library.reference.1=../../google-play-services_lib/play-services-ads-9.8.0
android.library.reference.2=../../google-play-services_lib/play-services-ads-lite-9.8.0
android.library.reference.3=../../google-play-services_lib/play-services-base-9.8.0
android.library.reference.4=../../google-play-services_lib/play-services-basement-9.8.0
android.library.reference.5=../../android-support-v4_lib`

**Comment by subsoap** [comment]
So this also means the potential 

  [dx] UNEXPECTED TOP-LEVEL EXCEPTION:
       [dx] com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536

problem solved in this version?

**Comment by subsoap** [comment]
I get this error when doing that.

`[aapt] \appodeal-monkeyx-demo-master\appodeal_example.buildv87a\android\bin\AndroidManifest.xml:62: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').`

**Comment by subsoap** [comment]
Could you upload a complete project / build folder to a zip so I can compare files?

**Comment by subsoap** [comment]
Tested on Windows and Mac now to make sure and still same issue. Edited the build.properties file to add the above lines, and still get this error:

[aapt] /appodeal-monkeyx-demo-master/appodeal_example.buildv87a/android/bin/AndroidManifest.xml:62: error: Error: No resource found that matches the given name (at 'value' with value '@integer/google_play_services_version').

**Comment by Tamplier** [comment]
@subsoap 
>method ID not in [0, 0xffff]: 65536

It's not possible to prevent this issue on plugin level. It happens because of many methods in Java code and android platform features.

>at 'value' with value '@integer/google_play_services_version'

Oh, sorry, I was wrong with build.properties. Real name of the file is "project.properties". Also, please check new lines in the file. Every android.library should be on new line.
Here is my [build folder](https://www.dropbox.com/s/sxyrbwzlxu86ldn/appodeal_example.buildv78h.zip?dl=0).

**Comment by subsoap** [comment]
Issue before was that with the older Appodeal MonkeyX module it appeared to needed to be converted to a Gradle project to properly be able to selectively compile the Google Play Services and not include the whole thing. What you have now appears to be a better way which won't do this and give more room?

Thank you for the files. The file which must be edited for more recent version of monkey is "\android\templates\project.properties"


There is another error

```
TRANS monkey compiler V1.87
Parsing...
Semanting...
Translating...
Building...
Buildfile: \appodeal-monkeyx-demo-master\appodeal_example.buildv87a\android\build.xml

-check-env:
 [checkenv] Android SDK Tools Revision 25.2.2
 [checkenv] Installed at \Android\sdk

-setup:
     [echo] Project Name: MonkeyGame
  [gettype] Project Type: Application

-pre-clean:

clean:
[getlibpath] Library dependencies:
[getlibpath] 
[getlibpath] ------------------
[getlibpath] Ordered libraries:

BUILD FAILED
\Android\sdk\tools\ant\build.xml:470: The following error occurred while executing this line:
\appodeal-monkeyx-demo-master\android-support-v4_lib\build.xml:9: Cannot find \appodeal-monkeyx-demo-master\android-support-v4_lib\${env.ANDROID_SDK}\tools\ant\build.xml imported from \appodeal-monkeyx-demo-master\android-support-v4_lib\build.xml

```

Other Android builds work. Tested on two different computers and on Mac/Linux to rule things out. I am still studying your build folder for anything that is missing. You built on 78h. I tested that version of Monkey too but get same error.

**Comment by NazarKozak** [comment]
@subsoap i've wrote you on the skype thread.
Try [this](https://s3.eu-central-1.amazonaws.com/appodeal-monkeyx/Appodeal-MonkeyX-060317-2.0.0.zip) one. Error you've sent should be fixed there. If it happens again, check if ANDROID_HOME is set in your System variables.
